package org.realityforge.keycloak.domgen;

import javax.annotation.Nonnull;
import javax.servlet.ServletRequest;

/**
 * Interface to implement so that the JndiBasedKeycloakConfigResolver can be customized by
 * by hand-wittend code while JndiBasedKeycloakConfigResolver is generated by domgen.
 */
public interface KeycloakUrlFilter
{
   /**
    * Return true if request should be protected by keycloakd.
    */
   boolean shouldProtectRequest( @Nonnull ServletRequest request );
}
